comments:
    # License in each file is unnecessary.
    AbsentOrWrongFileLicense:
        active: false
    # Nothing wrong with documenting private methods.
    CommentOverPrivateFunction:
        active: false
    # Nothing wrong with documenting private properties.
    CommentOverPrivateProperty:
        active: false

complexity:
    # Acceptable if used sparingly.
    LabeledExpression:
      active: false
    # Solved using resources bundled. All remaining duplicates are resource identifiers.
    StringLiteralDuplication:
      active: false
    # Static analysis is not good at estimating this.
    TooManyFunctions:
        thresholdInClasses: 20

formatting:
    # Bugged, see https://github.com/pinterest/ktlint/issues/1124
    AnnotationSpacing:
        active: false
    # Experimental. Too many false positives.
    ArgumentListWrapping:
        active: false
    # That's part of my code style.
    NoConsecutiveBlankLines:
        active: false
    # Acceptable because of auto-formatting.
    MultiLineIfElse:
        active: false

naming:
    # Static analysis is not good at estimating this.
    FunctionMaxLength:
        active: false
    # Cannot be suppressed in case of false positives
    MatchingDeclarationName:
        active: false

potential-bugs:
    # The alternative is to safe cast and throw an exception, which is equally bad.
    UnsafeCast:
        active: false

style:
    # Those functions are added as conscious design decisions.
    DataClassContainsFunctions:
        active: false
    # Not if they're settings objects.
    DataClassShouldBeImmutable:
        active: false
    # Not an issue if names are self-explanatory.
    DestructuringDeclarationWithTooManyEntries:
        active: false
    # Such comments are OK.
    ForbiddenComment:
        active: false
    # One more is fine in my opinion.
    LoopWithTooManyJumpStatements:
        maxJumpCount: 2
    # No braces are easier to read.
    MandatoryBracesIfStatements:
        active: false
    # Three is fine
    ReturnCount:
        max: 3
    # False positives when there are two newlines after the imports.
    SpacingBetweenPackageAndImports:
        active: false
