name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**.md'
      - '.github/img/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**.md'
      - '.github/img/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Run checks (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x ./gradlew
          sudo apt install -y xvfb
          xvfb-run --auto-servernum ./gradlew --no-daemon check
          ./gradlew --stop
      - name: Run checks (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          ./gradlew --no-daemon check
          ./gradlew --stop
      - uses: codecov/codecov-action@v3
        if: success() && matrix.os == 'ubuntu-latest'
        with:
          fail_ci_if_error: true
          files: build/reports/kover/xml/report.xml
